---
queries:
  
  nb.changes: >
    query Changes(
          $get_time: Boolean = false,
          $get_user_name: Boolean = false,
          $get_action: Boolean = false,
          $get_changed_object_id: Boolean = false,
          $get_change_context_detail: Boolean = false,
          $get_object_type: Boolean = false,
          __query_vars__
        ) {
        object_changes (__changes_params__) {
          time @include(if: $get_time)
          user_name @include(if: $get_user_name)
          action @include(if: $get_action)
          changed_object_id @include(if: $get_changed_object_id)
          changed_object_type @include(if: $get_object_type) { model }
          change_context_detail @include(if: $get_change_context_detail)
        }
    }

  nb.prefixes: >
    query Prefix(
        $get_id: Boolean = false,
        $get_prefix: Boolean = false,
        $get_prefix_length: Boolean = false, 
        $get_parent: Boolean = false,
        $get_type: Boolean = false,
        $get_description: Boolean = false,
        $get_location: Boolean = false,
        $get_ip_addresses: Boolean = false,
        $get_tags: Boolean = false, 
        $get_tenant: Boolean = false,
        $get_cf: Boolean = false,
        $get_custom_field_data: Boolean = false,
        $get__custom_field_data: Boolean = false,
        $get_primary_ip4_for: Boolean = false,
        $get_name: Boolean = false,
        $get_hostname: Boolean = false,
        $get_role: Boolean = false,
        $get_device_type: Boolean = false,
        $get_platform: Boolean = false,
        $get_serial: Boolean = false,
        $get_status: Boolean = false,
        $get_config_context: Boolean = false,
        $get_interfaces: Boolean = false,
        __query_vars__
      ) {
      prefixes (__prefixes_params__) {
        id @include(if: $get_id)
        prefix @include(if: $get_prefix)
        prefix_length @include(if: $get_prefix_length)
        parent @include(if: $get_parent) {
          prefix
        }
        description @include(if: $get_description)
        type @include(if: $get_type)
        location @include(if: $get_location) {
          name
        }
        _custom_field_data @include(if: $get_cf)
        _custom_field_data @include(if: $get__custom_field_data)
        custom_field_data : _custom_field_data @include(if: $get_custom_field_data)
        ip_addresses @include(if: $get_ip_addresses) {
          address
          primary_ip4_for(__primaryip4for_params__) @include(if: $get_primary_ip4_for) {
            id @include(if: $get_id)
          name @include(if: $get_name)
          hostname: name @include(if: $get_hostname)
          role @include(if: $get_role) {
            name
          }
          device_type @include(if: $get_device_type) {
            model
          }
          platform @include(if: $get_platform) {
            name
            manufacturer {
              name
            }
          }
          tags @include(if: $get_tags) {
            name
            content_types {
              id
              app_label
              model
            }
          }
          tenant @include(if: $get_tenant) {
            name
            tenant_group {
              name
            }
          }
          serial @include(if: $get_serial)
          status @include(if: $get_status) {
            name
          }
          config_context @include(if: $get_config_context)
          _custom_field_data @include(if: $get_cf)
          interfaces @include(if: $get_interfaces) {
            id
            name
            device {
              name
            }
            description
            enabled
            mac_address
            type
            mode
            ip_addresses {
              address
              role {
                id
              }
              tags {
                name
                content_types {
                  id
                  app_label
                  model
                }
              }
            }
            connected_circuit_termination {
              circuit {
                cid
                commit_rate
                provider {
                  name
                }
              }
            }
            tagged_vlans {
              name
              vid
            }
            untagged_vlan {
              name
              vid
            }
            cable {
              termination_a_type
              status {
                name
              }
              color
            }
            tags {
              name
              content_types {
                id
                app_label
                model
              }
            }
            lag {
              name
              enabled
            }
            member_interfaces {
              name
            }
          }
          location @include(if: $get_location) {
            name
          }
          }
        }
        tags @include(if: $get_tags) {
          name
          content_types {
            id
            app_label
            model
          }
        }
        tenant @include(if: $get_tenant) {
            name
            tenant_group {
              name
            }
        }
      }
    }

  nb.devices: >
    query Devices(
      $get_id: Boolean = false, 
      $get_name: Boolean = false, 
      $get_hostname: Boolean = true, 
      $get_interfaces: Boolean = false, 
      $get_location: Boolean = false, 
      $get_primary_ip4: Boolean = false, 
      $get_role: Boolean = false, 
      $get_device_type: Boolean = false, 
      $get_platform: Boolean = false, 
      $get_tags: Boolean = false, 
      $get_serial: Boolean = false, 
      $get_config_context: Boolean = false, 
      $get_cf: Boolean = false,
      $get_custom_field_data: Boolean = false,
      $get__custom_field_data: Boolean = false,
      $get_tenant: Boolean = false,
      __query_vars__
    ) {
      devices(__devices_params__) {
        id @include(if: $get_id)
        name @include(if: $get_name)
        hostname: name @include(if: $get_hostname)
        primary_ip4 @include(if: $get_primary_ip4) {
          address
        }
        role @include(if: $get_role) {
          name
        }
        device_type @include(if: $get_device_type) {
          model
        }
        platform @include(if: $get_platform) {
          name
          manufacturer {
            name
          }
        }
        tags @include(if: $get_tags) {
          name
          content_types {
            id
            app_label
            model
          }
        }
        tenant @include(if: $get_tenant) {
            name
            tenant_group {
              name
            }
        }
        serial @include(if: $get_serial)
        config_context @include(if: $get_config_context)
        _custom_field_data @include(if: $get_cf)
        _custom_field_data @include(if: $get__custom_field_data)
        custom_field_data : _custom_field_data @include(if: $get_custom_field_data)
        interfaces (__interfaces_params__) @include(if: $get_interfaces) {
          id
          name
          description
          enabled
          mac_address
          type
          mode
          ip_addresses {
            address
            role {
              id
            }
            tags {
              name
              content_types {
                id
                app_label
                model
              }
            }
          }
          connected_circuit_termination {
            circuit {
              cid
              commit_rate
              provider {
                name
              }
            }
          }
          tagged_vlans {
            name
            vid
          }
          untagged_vlan {
            name
            vid
          }
          cable {
            termination_a_type
            status {
              name
            }
            color
          }
          tags {
            name
            content_types {
              id
              app_label
              model
            }
          }
          lag {
            name
            enabled
          }
          member_interfaces {
            name
          }
        }
        location @include(if: $get_location) {
          name
        }
      }
    }

  nb.ipaddresses: >
    query IPadresses( 
          $get_id: Boolean = false, 
          $get_address: Boolean = false,
          $get_description: Boolean = false,
          $get_dns_name: Boolean = false,
          $get_parent: Boolean = false,
          $get_type: Boolean = false,
          $get_name: Boolean = false, 
          $get_hostname: Boolean = true, 
          $get_interfaces: Boolean = false, 
          $get_location: Boolean = false, 
          $get_primary_ip4_for: Boolean = false, 
          $get_role: Boolean = false, 
          $get_device_type: Boolean = false, 
          $get_platform: Boolean = false, 
          $get_tags: Boolean = false,
          $get_serial: Boolean = false,
          $get_status:  Boolean = false,
          $get_config_context: Boolean = false, 
          $get_cf: Boolean = false,
          $get_tenant: Boolean = false,
          __query_vars__
          ) {
      ip_addresses(__ipaddresses_params__) {
        id @include(if: $get_id)
        address @include(if: $get_address)
        description @include(if: $get_description)
        dns_name @include(if: $get_dns_name)
        type @include(if: $get_type)
        tags @include(if: $get_tags) {
          id
          name
        }
        parent @include(if: $get_parent) {
          network
          prefix
          prefix_length
        } 
        primary_ip4_for(__primaryip4for_params__) @include(if: $get_primary_ip4_for) {
          id @include(if: $get_id)
          name @include(if: $get_name)
          hostname: name @include(if: $get_hostname)
          role @include(if: $get_role) {
            name
          }
          device_type @include(if: $get_device_type) {
            model
          }
          platform @include(if: $get_platform) {
            name
            manufacturer {
              name
            }
          }
          tags @include(if: $get_tags) {
            name
            content_types {
              id
              app_label
              model
            }
          }
          tenant @include(if: $get_tenant) {
            name
            tenant_group {
              name
            }
          }
          serial @include(if: $get_serial)
          status @include(if: $get_status) {
            name
          }
          config_context @include(if: $get_config_context)
          _custom_field_data @include(if: $get_cf)
          interfaces (__interfaces_params__) @include(if: $get_interfaces) {
            id
            name
            device {
              name
            }
            description
            enabled
            mac_address
            type
            mode
            ip_addresses {
              address
              role {
                id
              }
              tags {
                name
                content_types {
                  id
                  app_label
                  model
                }
              }
            }
            connected_circuit_termination {
              circuit {
                cid
                commit_rate
                provider {
                  name
                }
              }
            }
            tagged_vlans {
              name
              vid
            }
            untagged_vlan {
              name
              vid
            }
            cable {
              termination_a_type
              status {
                name
              }
              color
            }
            tags {
              name
              content_types {
                id
                app_label
                model
              }
            }
            lag {
              name
              enabled
            }
            member_interfaces {
              name
            }
          }
          location @include(if: $get_location) {
            name
          }
        }
      }
    }

  nb.vlans: >
    query Vlans(
        $get_id: Boolean = false,
        $get_vid: Boolean = false, 
        $get_name: Boolean = false, 
        $get_status: Boolean = false,
        $get_role: Boolean = false,
        $get_description: Boolean = false,
        $get_location: Boolean = false,
        $get_vlan_group: Boolean = false,
        $get_tenant: Boolean = false,
        $get_tags: Boolean = false,
        __query_vars__
      ) {
      vlans(__vlans_params__) {
        id @include(if: $get_id)
        vid @include(if: $get_vid)
        name @include(if: $get_name)
        status @include(if: $get_status) {
          name
        }
        role @include(if: $get_role) {name}
        description @include(if: $get_description)
        location @include(if: $get_location) {name}
        vlan_group @include(if: $get_vlan_group) {name}
        tenant @include(if: $get_tenant) {
            name
            tenant_group {
              name
            }
        }
        tags @include(if: $get_tags) {
          name
          content_types {
            id
            app_label
            model
          }
        }
      }
    }

  nb.general: >
    query General(
      $get_locations: Boolean = false,
      $get_tags: Boolean = false,
      __query_vars__
    ) {
      locations(__general_params__) @include(if: $get_locations) {name}
      tags(__general_params__) @include(if: $get_tags) {
        name
        content_types {
          id
          app_label
          model
        }
      }
    }

analyzer:
  config: ../conf/sot/analyzer/analyzer.yaml

configparser:
  config: ../conf/sot/configparser/configparser.yaml
  
journal:
  config: ../conf/journal/config.yaml

devicemanagement:
  config: ../conf/devicemanagement/

templates:
    directory: "../../../veritasData/templates/"
    trim_blocks: True

inventory:
    backup_configs: "../../../veritasData/config_backups"

webhooks:
    dcim.device:
        create:
            routing_key: device.create
        update:
            routing_key: device.update
        delete:
            routing_key: device.delete
